# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/christian/CLionProjects/RESTProxy

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/christian/CLionProjects/RESTProxy

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/christian/CLionProjects/RESTProxy/CMakeFiles /home/christian/CLionProjects/RESTProxy/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/christian/CLionProjects/RESTProxy/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ContinuousSubmit

# Build rule for target.
ContinuousSubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousSubmit
.PHONY : ContinuousSubmit

# fast build rule for target.
ContinuousSubmit/fast:
	$(MAKE) -f CMakeFiles/ContinuousSubmit.dir/build.make CMakeFiles/ContinuousSubmit.dir/build
.PHONY : ContinuousSubmit/fast

#=============================================================================
# Target rules for targets named ContinuousMemCheck

# Build rule for target.
ContinuousMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousMemCheck
.PHONY : ContinuousMemCheck

# fast build rule for target.
ContinuousMemCheck/fast:
	$(MAKE) -f CMakeFiles/ContinuousMemCheck.dir/build.make CMakeFiles/ContinuousMemCheck.dir/build
.PHONY : ContinuousMemCheck/fast

#=============================================================================
# Target rules for targets named ContinuousConfigure

# Build rule for target.
ContinuousConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousConfigure
.PHONY : ContinuousConfigure

# fast build rule for target.
ContinuousConfigure/fast:
	$(MAKE) -f CMakeFiles/ContinuousConfigure.dir/build.make CMakeFiles/ContinuousConfigure.dir/build
.PHONY : ContinuousConfigure/fast

#=============================================================================
# Target rules for targets named ExperimentalSubmit

# Build rule for target.
ExperimentalSubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalSubmit
.PHONY : ExperimentalSubmit

# fast build rule for target.
ExperimentalSubmit/fast:
	$(MAKE) -f CMakeFiles/ExperimentalSubmit.dir/build.make CMakeFiles/ExperimentalSubmit.dir/build
.PHONY : ExperimentalSubmit/fast

#=============================================================================
# Target rules for targets named ExperimentalMemCheck

# Build rule for target.
ExperimentalMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalMemCheck
.PHONY : ExperimentalMemCheck

# fast build rule for target.
ExperimentalMemCheck/fast:
	$(MAKE) -f CMakeFiles/ExperimentalMemCheck.dir/build.make CMakeFiles/ExperimentalMemCheck.dir/build
.PHONY : ExperimentalMemCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalTest

# Build rule for target.
ExperimentalTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalTest
.PHONY : ExperimentalTest

# fast build rule for target.
ExperimentalTest/fast:
	$(MAKE) -f CMakeFiles/ExperimentalTest.dir/build.make CMakeFiles/ExperimentalTest.dir/build
.PHONY : ExperimentalTest/fast

#=============================================================================
# Target rules for targets named NightlyUpdate

# Build rule for target.
NightlyUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyUpdate
.PHONY : NightlyUpdate

# fast build rule for target.
NightlyUpdate/fast:
	$(MAKE) -f CMakeFiles/NightlyUpdate.dir/build.make CMakeFiles/NightlyUpdate.dir/build
.PHONY : NightlyUpdate/fast

#=============================================================================
# Target rules for targets named NightlyStart

# Build rule for target.
NightlyStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyStart
.PHONY : NightlyStart

# fast build rule for target.
NightlyStart/fast:
	$(MAKE) -f CMakeFiles/NightlyStart.dir/build.make CMakeFiles/NightlyStart.dir/build
.PHONY : NightlyStart/fast

#=============================================================================
# Target rules for targets named NightlyMemoryCheck

# Build rule for target.
NightlyMemoryCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyMemoryCheck
.PHONY : NightlyMemoryCheck

# fast build rule for target.
NightlyMemoryCheck/fast:
	$(MAKE) -f CMakeFiles/NightlyMemoryCheck.dir/build.make CMakeFiles/NightlyMemoryCheck.dir/build
.PHONY : NightlyMemoryCheck/fast

#=============================================================================
# Target rules for targets named NightlyBuild

# Build rule for target.
NightlyBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyBuild
.PHONY : NightlyBuild

# fast build rule for target.
NightlyBuild/fast:
	$(MAKE) -f CMakeFiles/NightlyBuild.dir/build.make CMakeFiles/NightlyBuild.dir/build
.PHONY : NightlyBuild/fast

#=============================================================================
# Target rules for targets named ExperimentalUpdate

# Build rule for target.
ExperimentalUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalUpdate
.PHONY : ExperimentalUpdate

# fast build rule for target.
ExperimentalUpdate/fast:
	$(MAKE) -f CMakeFiles/ExperimentalUpdate.dir/build.make CMakeFiles/ExperimentalUpdate.dir/build
.PHONY : ExperimentalUpdate/fast

#=============================================================================
# Target rules for targets named ContinuousBuild

# Build rule for target.
ContinuousBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousBuild
.PHONY : ContinuousBuild

# fast build rule for target.
ContinuousBuild/fast:
	$(MAKE) -f CMakeFiles/ContinuousBuild.dir/build.make CMakeFiles/ContinuousBuild.dir/build
.PHONY : ContinuousBuild/fast

#=============================================================================
# Target rules for targets named Continuous

# Build rule for target.
Continuous: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Continuous
.PHONY : Continuous

# fast build rule for target.
Continuous/fast:
	$(MAKE) -f CMakeFiles/Continuous.dir/build.make CMakeFiles/Continuous.dir/build
.PHONY : Continuous/fast

#=============================================================================
# Target rules for targets named Experimental

# Build rule for target.
Experimental: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Experimental
.PHONY : Experimental

# fast build rule for target.
Experimental/fast:
	$(MAKE) -f CMakeFiles/Experimental.dir/build.make CMakeFiles/Experimental.dir/build
.PHONY : Experimental/fast

#=============================================================================
# Target rules for targets named ExperimentalConfigure

# Build rule for target.
ExperimentalConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalConfigure
.PHONY : ExperimentalConfigure

# fast build rule for target.
ExperimentalConfigure/fast:
	$(MAKE) -f CMakeFiles/ExperimentalConfigure.dir/build.make CMakeFiles/ExperimentalConfigure.dir/build
.PHONY : ExperimentalConfigure/fast

#=============================================================================
# Target rules for targets named NightlyTest

# Build rule for target.
NightlyTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyTest
.PHONY : NightlyTest

# fast build rule for target.
NightlyTest/fast:
	$(MAKE) -f CMakeFiles/NightlyTest.dir/build.make CMakeFiles/NightlyTest.dir/build
.PHONY : NightlyTest/fast

#=============================================================================
# Target rules for targets named NightlyCoverage

# Build rule for target.
NightlyCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyCoverage
.PHONY : NightlyCoverage

# fast build rule for target.
NightlyCoverage/fast:
	$(MAKE) -f CMakeFiles/NightlyCoverage.dir/build.make CMakeFiles/NightlyCoverage.dir/build
.PHONY : NightlyCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalCoverage

# Build rule for target.
ExperimentalCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalCoverage
.PHONY : ExperimentalCoverage

# fast build rule for target.
ExperimentalCoverage/fast:
	$(MAKE) -f CMakeFiles/ExperimentalCoverage.dir/build.make CMakeFiles/ExperimentalCoverage.dir/build
.PHONY : ExperimentalCoverage/fast

#=============================================================================
# Target rules for targets named NightlyMemCheck

# Build rule for target.
NightlyMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyMemCheck
.PHONY : NightlyMemCheck

# fast build rule for target.
NightlyMemCheck/fast:
	$(MAKE) -f CMakeFiles/NightlyMemCheck.dir/build.make CMakeFiles/NightlyMemCheck.dir/build
.PHONY : NightlyMemCheck/fast

#=============================================================================
# Target rules for targets named ContinuousStart

# Build rule for target.
ContinuousStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousStart
.PHONY : ContinuousStart

# fast build rule for target.
ContinuousStart/fast:
	$(MAKE) -f CMakeFiles/ContinuousStart.dir/build.make CMakeFiles/ContinuousStart.dir/build
.PHONY : ContinuousStart/fast

#=============================================================================
# Target rules for targets named NightlySubmit

# Build rule for target.
NightlySubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlySubmit
.PHONY : NightlySubmit

# fast build rule for target.
NightlySubmit/fast:
	$(MAKE) -f CMakeFiles/NightlySubmit.dir/build.make CMakeFiles/NightlySubmit.dir/build
.PHONY : NightlySubmit/fast

#=============================================================================
# Target rules for targets named ContinuousCoverage

# Build rule for target.
ContinuousCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousCoverage
.PHONY : ContinuousCoverage

# fast build rule for target.
ContinuousCoverage/fast:
	$(MAKE) -f CMakeFiles/ContinuousCoverage.dir/build.make CMakeFiles/ContinuousCoverage.dir/build
.PHONY : ContinuousCoverage/fast

#=============================================================================
# Target rules for targets named Nightly

# Build rule for target.
Nightly: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Nightly
.PHONY : Nightly

# fast build rule for target.
Nightly/fast:
	$(MAKE) -f CMakeFiles/Nightly.dir/build.make CMakeFiles/Nightly.dir/build
.PHONY : Nightly/fast

#=============================================================================
# Target rules for targets named NightlyConfigure

# Build rule for target.
NightlyConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyConfigure
.PHONY : NightlyConfigure

# fast build rule for target.
NightlyConfigure/fast:
	$(MAKE) -f CMakeFiles/NightlyConfigure.dir/build.make CMakeFiles/NightlyConfigure.dir/build
.PHONY : NightlyConfigure/fast

#=============================================================================
# Target rules for targets named ExperimentalStart

# Build rule for target.
ExperimentalStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalStart
.PHONY : ExperimentalStart

# fast build rule for target.
ExperimentalStart/fast:
	$(MAKE) -f CMakeFiles/ExperimentalStart.dir/build.make CMakeFiles/ExperimentalStart.dir/build
.PHONY : ExperimentalStart/fast

#=============================================================================
# Target rules for targets named ContinuousTest

# Build rule for target.
ContinuousTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousTest
.PHONY : ContinuousTest

# fast build rule for target.
ContinuousTest/fast:
	$(MAKE) -f CMakeFiles/ContinuousTest.dir/build.make CMakeFiles/ContinuousTest.dir/build
.PHONY : ContinuousTest/fast

#=============================================================================
# Target rules for targets named ContinuousUpdate

# Build rule for target.
ContinuousUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousUpdate
.PHONY : ContinuousUpdate

# fast build rule for target.
ContinuousUpdate/fast:
	$(MAKE) -f CMakeFiles/ContinuousUpdate.dir/build.make CMakeFiles/ContinuousUpdate.dir/build
.PHONY : ContinuousUpdate/fast

#=============================================================================
# Target rules for targets named ExperimentalBuild

# Build rule for target.
ExperimentalBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalBuild
.PHONY : ExperimentalBuild

# fast build rule for target.
ExperimentalBuild/fast:
	$(MAKE) -f CMakeFiles/ExperimentalBuild.dir/build.make CMakeFiles/ExperimentalBuild.dir/build
.PHONY : ExperimentalBuild/fast

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) -f src/CMakeFiles/main.dir/build.make src/CMakeFiles/main.dir/build
.PHONY : main/fast

#=============================================================================
# Target rules for targets named request_reply.o

# Build rule for target.
request_reply.o: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 request_reply.o
.PHONY : request_reply.o

# fast build rule for target.
request_reply.o/fast:
	$(MAKE) -f src/CMakeFiles/request_reply.o.dir/build.make src/CMakeFiles/request_reply.o.dir/build
.PHONY : request_reply.o/fast

#=============================================================================
# Target rules for targets named route.o

# Build rule for target.
route.o: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 route.o
.PHONY : route.o

# fast build rule for target.
route.o/fast:
	$(MAKE) -f src/CMakeFiles/route.o.dir/build.make src/CMakeFiles/route.o.dir/build
.PHONY : route.o/fast

#=============================================================================
# Target rules for targets named workflow_handler.o

# Build rule for target.
workflow_handler.o: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 workflow_handler.o
.PHONY : workflow_handler.o

# fast build rule for target.
workflow_handler.o/fast:
	$(MAKE) -f src/CMakeFiles/workflow_handler.o.dir/build.make src/CMakeFiles/workflow_handler.o.dir/build
.PHONY : workflow_handler.o/fast

#=============================================================================
# Target rules for targets named route_instance.o

# Build rule for target.
route_instance.o: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 route_instance.o
.PHONY : route_instance.o

# fast build rule for target.
route_instance.o/fast:
	$(MAKE) -f src/CMakeFiles/route_instance.o.dir/build.make src/CMakeFiles/route_instance.o.dir/build
.PHONY : route_instance.o/fast

#=============================================================================
# Target rules for targets named file_connector.o

# Build rule for target.
file_connector.o: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 file_connector.o
.PHONY : file_connector.o

# fast build rule for target.
file_connector.o/fast:
	$(MAKE) -f src/CMakeFiles/file_connector.o.dir/build.make src/CMakeFiles/file_connector.o.dir/build
.PHONY : file_connector.o/fast

#=============================================================================
# Target rules for targets named gateway

# Build rule for target.
gateway: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gateway
.PHONY : gateway

# fast build rule for target.
gateway/fast:
	$(MAKE) -f src/CMakeFiles/gateway.dir/build.make src/CMakeFiles/gateway.dir/build
.PHONY : gateway/fast

#=============================================================================
# Target rules for targets named http_connection.o

# Build rule for target.
http_connection.o: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 http_connection.o
.PHONY : http_connection.o

# fast build rule for target.
http_connection.o/fast:
	$(MAKE) -f src/http/CMakeFiles/http_connection.o.dir/build.make src/http/CMakeFiles/http_connection.o.dir/build
.PHONY : http_connection.o/fast

#=============================================================================
# Target rules for targets named http_message.o

# Build rule for target.
http_message.o: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 http_message.o
.PHONY : http_message.o

# fast build rule for target.
http_message.o/fast:
	$(MAKE) -f src/http/CMakeFiles/http_message.o.dir/build.make src/http/CMakeFiles/http_message.o.dir/build
.PHONY : http_message.o/fast

#=============================================================================
# Target rules for targets named http

# Build rule for target.
http: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 http
.PHONY : http

# fast build rule for target.
http/fast:
	$(MAKE) -f src/http/CMakeFiles/http.dir/build.make src/http/CMakeFiles/http.dir/build
.PHONY : http/fast

#=============================================================================
# Target rules for targets named http_first_line.o

# Build rule for target.
http_first_line.o: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 http_first_line.o
.PHONY : http_first_line.o

# fast build rule for target.
http_first_line.o/fast:
	$(MAKE) -f src/http/CMakeFiles/http_first_line.o.dir/build.make src/http/CMakeFiles/http_first_line.o.dir/build
.PHONY : http_first_line.o/fast

#=============================================================================
# Target rules for targets named http_headers.o

# Build rule for target.
http_headers.o: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 http_headers.o
.PHONY : http_headers.o

# fast build rule for target.
http_headers.o/fast:
	$(MAKE) -f src/http/CMakeFiles/http_headers.o.dir/build.make src/http/CMakeFiles/http_headers.o.dir/build
.PHONY : http_headers.o/fast

#=============================================================================
# Target rules for targets named http_request.o

# Build rule for target.
http_request.o: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 http_request.o
.PHONY : http_request.o

# fast build rule for target.
http_request.o/fast:
	$(MAKE) -f src/http/CMakeFiles/http_request.o.dir/build.make src/http/CMakeFiles/http_request.o.dir/build
.PHONY : http_request.o/fast

#=============================================================================
# Target rules for targets named http_reply.o

# Build rule for target.
http_reply.o: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 http_reply.o
.PHONY : http_reply.o

# fast build rule for target.
http_reply.o/fast:
	$(MAKE) -f src/http/CMakeFiles/http_reply.o.dir/build.make src/http/CMakeFiles/http_reply.o.dir/build
.PHONY : http_reply.o/fast

#=============================================================================
# Target rules for targets named socket_wrap.o

# Build rule for target.
socket_wrap.o: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 socket_wrap.o
.PHONY : socket_wrap.o

# fast build rule for target.
socket_wrap.o/fast:
	$(MAKE) -f src/socket/CMakeFiles/socket_wrap.o.dir/build.make src/socket/CMakeFiles/socket_wrap.o.dir/build
.PHONY : socket_wrap.o/fast

#=============================================================================
# Target rules for targets named socket_conn

# Build rule for target.
socket_conn: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 socket_conn
.PHONY : socket_conn

# fast build rule for target.
socket_conn/fast:
	$(MAKE) -f src/socket/CMakeFiles/socket_conn.dir/build.make src/socket/CMakeFiles/socket_conn.dir/build
.PHONY : socket_conn/fast

#=============================================================================
# Target rules for targets named socket_connector.o

# Build rule for target.
socket_connector.o: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 socket_connector.o
.PHONY : socket_connector.o

# fast build rule for target.
socket_connector.o/fast:
	$(MAKE) -f src/socket/CMakeFiles/socket_connector.o.dir/build.make src/socket/CMakeFiles/socket_connector.o.dir/build
.PHONY : socket_connector.o/fast

#=============================================================================
# Target rules for targets named circular_buffer.o

# Build rule for target.
circular_buffer.o: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 circular_buffer.o
.PHONY : circular_buffer.o

# fast build rule for target.
circular_buffer.o/fast:
	$(MAKE) -f src/buffers/CMakeFiles/circular_buffer.o.dir/build.make src/buffers/CMakeFiles/circular_buffer.o.dir/build
.PHONY : circular_buffer.o/fast

#=============================================================================
# Target rules for targets named buffers

# Build rule for target.
buffers: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 buffers
.PHONY : buffers

# fast build rule for target.
buffers/fast:
	$(MAKE) -f src/buffers/CMakeFiles/buffers.dir/build.make src/buffers/CMakeFiles/buffers.dir/build
.PHONY : buffers/fast

#=============================================================================
# Target rules for targets named shared_buffers.o

# Build rule for target.
shared_buffers.o: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 shared_buffers.o
.PHONY : shared_buffers.o

# fast build rule for target.
shared_buffers.o/fast:
	$(MAKE) -f src/buffers/CMakeFiles/shared_buffers.o.dir/build.make src/buffers/CMakeFiles/shared_buffers.o.dir/build
.PHONY : shared_buffers.o/fast

#=============================================================================
# Target rules for targets named rest_logs

# Build rule for target.
rest_logs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rest_logs
.PHONY : rest_logs

# fast build rule for target.
rest_logs/fast:
	$(MAKE) -f src/logs/CMakeFiles/rest_logs.dir/build.make src/logs/CMakeFiles/rest_logs.dir/build
.PHONY : rest_logs/fast

#=============================================================================
# Target rules for targets named shared_buffers_TEST_test

# Build rule for target.
shared_buffers_TEST_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 shared_buffers_TEST_test
.PHONY : shared_buffers_TEST_test

# fast build rule for target.
shared_buffers_TEST_test/fast:
	$(MAKE) -f tests/CMakeFiles/shared_buffers_TEST_test.dir/build.make tests/CMakeFiles/shared_buffers_TEST_test.dir/build
.PHONY : shared_buffers_TEST_test/fast

#=============================================================================
# Target rules for targets named mock_socket_connector_TEST

# Build rule for target.
mock_socket_connector_TEST: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mock_socket_connector_TEST
.PHONY : mock_socket_connector_TEST

# fast build rule for target.
mock_socket_connector_TEST/fast:
	$(MAKE) -f tests/CMakeFiles/mock_socket_connector_TEST.dir/build.make tests/CMakeFiles/mock_socket_connector_TEST.dir/build
.PHONY : mock_socket_connector_TEST/fast

#=============================================================================
# Target rules for targets named http_first_line_TEST_test

# Build rule for target.
http_first_line_TEST_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 http_first_line_TEST_test
.PHONY : http_first_line_TEST_test

# fast build rule for target.
http_first_line_TEST_test/fast:
	$(MAKE) -f tests/CMakeFiles/http_first_line_TEST_test.dir/build.make tests/CMakeFiles/http_first_line_TEST_test.dir/build
.PHONY : http_first_line_TEST_test/fast

#=============================================================================
# Target rules for targets named socket_connector_TEST_test

# Build rule for target.
socket_connector_TEST_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 socket_connector_TEST_test
.PHONY : socket_connector_TEST_test

# fast build rule for target.
socket_connector_TEST_test/fast:
	$(MAKE) -f tests/CMakeFiles/socket_connector_TEST_test.dir/build.make tests/CMakeFiles/socket_connector_TEST_test.dir/build
.PHONY : socket_connector_TEST_test/fast

#=============================================================================
# Target rules for targets named mock_pthread.o

# Build rule for target.
mock_pthread.o: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mock_pthread.o
.PHONY : mock_pthread.o

# fast build rule for target.
mock_pthread.o/fast:
	$(MAKE) -f tests/mocks/CMakeFiles/mock_pthread.o.dir/build.make tests/mocks/CMakeFiles/mock_pthread.o.dir/build
.PHONY : mock_pthread.o/fast

#=============================================================================
# Target rules for targets named socket_connector_ut.o

# Build rule for target.
socket_connector_ut.o: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 socket_connector_ut.o
.PHONY : socket_connector_ut.o

# fast build rule for target.
socket_connector_ut.o/fast:
	$(MAKE) -f tests/mocks/CMakeFiles/socket_connector_ut.o.dir/build.make tests/mocks/CMakeFiles/socket_connector_ut.o.dir/build
.PHONY : socket_connector_ut.o/fast

#=============================================================================
# Target rules for targets named mock_circular_buffers.o

# Build rule for target.
mock_circular_buffers.o: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mock_circular_buffers.o
.PHONY : mock_circular_buffers.o

# fast build rule for target.
mock_circular_buffers.o/fast:
	$(MAKE) -f tests/mocks/CMakeFiles/mock_circular_buffers.o.dir/build.make tests/mocks/CMakeFiles/mock_circular_buffers.o.dir/build
.PHONY : mock_circular_buffers.o/fast

#=============================================================================
# Target rules for targets named mock_shared_buffers.o

# Build rule for target.
mock_shared_buffers.o: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mock_shared_buffers.o
.PHONY : mock_shared_buffers.o

# fast build rule for target.
mock_shared_buffers.o/fast:
	$(MAKE) -f tests/mocks/CMakeFiles/mock_shared_buffers.o.dir/build.make tests/mocks/CMakeFiles/mock_shared_buffers.o.dir/build
.PHONY : mock_shared_buffers.o/fast

#=============================================================================
# Target rules for targets named mock_socket.o

# Build rule for target.
mock_socket.o: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mock_socket.o
.PHONY : mock_socket.o

# fast build rule for target.
mock_socket.o/fast:
	$(MAKE) -f tests/mocks/CMakeFiles/mock_socket.o.dir/build.make tests/mocks/CMakeFiles/mock_socket.o.dir/build
.PHONY : mock_socket.o/fast

#=============================================================================
# Target rules for targets named mock_file_connector.o

# Build rule for target.
mock_file_connector.o: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mock_file_connector.o
.PHONY : mock_file_connector.o

# fast build rule for target.
mock_file_connector.o/fast:
	$(MAKE) -f tests/mocks/CMakeFiles/mock_file_connector.o.dir/build.make tests/mocks/CMakeFiles/mock_file_connector.o.dir/build
.PHONY : mock_file_connector.o/fast

#=============================================================================
# Target rules for targets named mock_http_message.o

# Build rule for target.
mock_http_message.o: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mock_http_message.o
.PHONY : mock_http_message.o

# fast build rule for target.
mock_http_message.o/fast:
	$(MAKE) -f tests/mocks/CMakeFiles/mock_http_message.o.dir/build.make tests/mocks/CMakeFiles/mock_http_message.o.dir/build
.PHONY : mock_http_message.o/fast

#=============================================================================
# Target rules for targets named mock_socket_connector.o

# Build rule for target.
mock_socket_connector.o: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mock_socket_connector.o
.PHONY : mock_socket_connector.o

# fast build rule for target.
mock_socket_connector.o/fast:
	$(MAKE) -f tests/mocks/CMakeFiles/mock_socket_connector.o.dir/build.make tests/mocks/CMakeFiles/mock_socket_connector.o.dir/build
.PHONY : mock_socket_connector.o/fast

#=============================================================================
# Target rules for targets named mock_http_headers.o

# Build rule for target.
mock_http_headers.o: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mock_http_headers.o
.PHONY : mock_http_headers.o

# fast build rule for target.
mock_http_headers.o/fast:
	$(MAKE) -f tests/mocks/CMakeFiles/mock_http_headers.o.dir/build.make tests/mocks/CMakeFiles/mock_http_headers.o.dir/build
.PHONY : mock_http_headers.o/fast

#=============================================================================
# Target rules for targets named mock_first_line.o

# Build rule for target.
mock_first_line.o: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mock_first_line.o
.PHONY : mock_first_line.o

# fast build rule for target.
mock_first_line.o/fast:
	$(MAKE) -f tests/mocks/CMakeFiles/mock_first_line.o.dir/build.make tests/mocks/CMakeFiles/mock_first_line.o.dir/build
.PHONY : mock_first_line.o/fast

#=============================================================================
# Target rules for targets named circular_buffer_TEST

# Build rule for target.
circular_buffer_TEST: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 circular_buffer_TEST
.PHONY : circular_buffer_TEST

# fast build rule for target.
circular_buffer_TEST/fast:
	$(MAKE) -f tests/buffers/CMakeFiles/circular_buffer_TEST.dir/build.make tests/buffers/CMakeFiles/circular_buffer_TEST.dir/build
.PHONY : circular_buffer_TEST/fast

#=============================================================================
# Target rules for targets named http_headers_TEST

# Build rule for target.
http_headers_TEST: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 http_headers_TEST
.PHONY : http_headers_TEST

# fast build rule for target.
http_headers_TEST/fast:
	$(MAKE) -f tests/http/CMakeFiles/http_headers_TEST.dir/build.make tests/http/CMakeFiles/http_headers_TEST.dir/build
.PHONY : http_headers_TEST/fast

#=============================================================================
# Target rules for targets named http_message_TEST

# Build rule for target.
http_message_TEST: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 http_message_TEST
.PHONY : http_message_TEST

# fast build rule for target.
http_message_TEST/fast:
	$(MAKE) -f tests/http/CMakeFiles/http_message_TEST.dir/build.make tests/http/CMakeFiles/http_message_TEST.dir/build
.PHONY : http_message_TEST/fast

#=============================================================================
# Target rules for targets named http_request_TEST

# Build rule for target.
http_request_TEST: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 http_request_TEST
.PHONY : http_request_TEST

# fast build rule for target.
http_request_TEST/fast:
	$(MAKE) -f tests/http/CMakeFiles/http_request_TEST.dir/build.make tests/http/CMakeFiles/http_request_TEST.dir/build
.PHONY : http_request_TEST/fast

#=============================================================================
# Target rules for targets named decode_http_headers

# Build rule for target.
decode_http_headers: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 decode_http_headers
.PHONY : decode_http_headers

# fast build rule for target.
decode_http_headers/fast:
	$(MAKE) -f tests/http/CMakeFiles/decode_http_headers.dir/build.make tests/http/CMakeFiles/decode_http_headers.dir/build
.PHONY : decode_http_headers/fast

#=============================================================================
# Target rules for targets named http_reply_TEST

# Build rule for target.
http_reply_TEST: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 http_reply_TEST
.PHONY : http_reply_TEST

# fast build rule for target.
http_reply_TEST/fast:
	$(MAKE) -f tests/http/CMakeFiles/http_reply_TEST.dir/build.make tests/http/CMakeFiles/http_reply_TEST.dir/build
.PHONY : http_reply_TEST/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... ContinuousSubmit"
	@echo "... ContinuousMemCheck"
	@echo "... ContinuousConfigure"
	@echo "... ExperimentalSubmit"
	@echo "... ExperimentalMemCheck"
	@echo "... ExperimentalTest"
	@echo "... NightlyUpdate"
	@echo "... NightlyStart"
	@echo "... NightlyMemoryCheck"
	@echo "... NightlyBuild"
	@echo "... ExperimentalUpdate"
	@echo "... ContinuousBuild"
	@echo "... Continuous"
	@echo "... Experimental"
	@echo "... ExperimentalConfigure"
	@echo "... edit_cache"
	@echo "... NightlyTest"
	@echo "... NightlyCoverage"
	@echo "... ExperimentalCoverage"
	@echo "... NightlyMemCheck"
	@echo "... ContinuousStart"
	@echo "... NightlySubmit"
	@echo "... ContinuousCoverage"
	@echo "... Nightly"
	@echo "... NightlyConfigure"
	@echo "... ExperimentalStart"
	@echo "... ContinuousTest"
	@echo "... ContinuousUpdate"
	@echo "... ExperimentalBuild"
	@echo "... main"
	@echo "... request_reply.o"
	@echo "... route.o"
	@echo "... workflow_handler.o"
	@echo "... route_instance.o"
	@echo "... file_connector.o"
	@echo "... gateway"
	@echo "... http_connection.o"
	@echo "... http_message.o"
	@echo "... http"
	@echo "... http_first_line.o"
	@echo "... http_headers.o"
	@echo "... http_request.o"
	@echo "... http_reply.o"
	@echo "... socket_wrap.o"
	@echo "... socket_conn"
	@echo "... socket_connector.o"
	@echo "... circular_buffer.o"
	@echo "... buffers"
	@echo "... shared_buffers.o"
	@echo "... rest_logs"
	@echo "... shared_buffers_TEST_test"
	@echo "... mock_socket_connector_TEST"
	@echo "... http_first_line_TEST_test"
	@echo "... socket_connector_TEST_test"
	@echo "... mock_pthread.o"
	@echo "... socket_connector_ut.o"
	@echo "... mock_circular_buffers.o"
	@echo "... mock_shared_buffers.o"
	@echo "... mock_socket.o"
	@echo "... mock_file_connector.o"
	@echo "... mock_http_message.o"
	@echo "... mock_socket_connector.o"
	@echo "... mock_http_headers.o"
	@echo "... mock_first_line.o"
	@echo "... circular_buffer_TEST"
	@echo "... http_headers_TEST"
	@echo "... http_message_TEST"
	@echo "... http_request_TEST"
	@echo "... decode_http_headers"
	@echo "... http_reply_TEST"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

